### Create Admin User
POST http://localhost:8000/api/auth/register-admin
Content-Type: application/json

{
  "name": "Super Admin",
  "email": "admin@medimind.com",
  "password": "admin123"
}

### Login Admin
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "admin@medimind.com",
  "password": "admin123"
}